### ISSUE TITLE
Add "standalone" page for git + jupyter

### ISSUE THREAD

**Issue by qdread** [SESYNC-ci/basic-git-lesson#6]
Following the model of pages like [this one from the basic r lesson](https://cyberhelp.sesync.org/basic-R-lesson/2020/07/21/rstudio_ide.html).

Include some basic material about using git in jupyter in case people navigate to this lesson who want to use Python and aren't interested in RStudio.

See [our cyberhelp faq](https://cyberhelp.sesync.org/faq/git-and-jupyterlab.html) on it, and [this carpentries lesson](https://annefou.github.io/jupyter_publish/02-git/index.html).

**Comment by andGarc** [comment]
Draft: https://andgarc.github.io/basic-git-jupyter-lesson/#/slides/intro
I just realized that we already have a section on pull requests so I will remove that.

**Comment by andGarc** [comment]
I merged the pull request. 
Link to the standalone page has been added under the RStudio + git section.
[RStudio + git section](http://cyberhelp.sesync.org/basic-git-lesson/#/slides/config).
